const message = {
    USER_REGISTRATION: "User Registration successfully!",
    USER_LOGIN: "User login successfully!",
    ERROR_MESSAGE: "Unexpected error occurred!",
    PASSWORD_REQUIRED: "Password is required! ",
    PASSWORD_CHARACTER: "Password must be at least 8 characters long!",
    PASSWORD_MATCH: "Password not match,please check your password!",
    PASSWORD_REQUIRED_CHARACTER: "Password must be at least 8 characters long!",
    PASSWORD_NOT_MATCH: "Password did not match,please check your password!",
    EMAIL_ALREADY_EXISTS: "Email already exists please enter another email!",
    EMAIL_PASSWORD_WRONG: "Email and Password Wrong!",
    DATA_NOT_FOUND: "User data not found!",
    ALREADY_EXISTS: "You are already exists!",
    EMAIL_NOT_MATCH: "This email address does not exists!",
    EMAIL_VERIFIED: "Email verified successfully!",
    PASSWORD_UPDATED: "Password updated successfully!",
    USER_PROFILE_UPDATE: "User profile update successfully!",
    USER_LOGOUT: "User logout successfully!",
    NEWS_DATA_CREATED: "News data created successfully!",
    NEWS_DATA_UPDATED: "News data updated successfully!",
    NEWS_DATA_DETAILS: "News data details successfully!",
    NEWS_DATA_DELETED: "News data deleted successfully!",
    ALREADY_DELETED: "News data alredy deleted successfully!",
    PASSWORD_INCORRECT: "Password incorrect ,plese check your password!",
    PASSWORD_CHECKED: "Password mismatch,please check your password!",
    PASSWORD_NOT_UPDATED: "Password did n't updated!",
    CHANGED_PASSWORD: "Password change successfully!",
    OLD_PASSWORD: "Incorrect password,Please check your old password!",
    CONFIRM_PASSWORD: "Confirm password is required",
    HEADER_CREATED: "Header created successfully!",
    HEADERDETAILS_SUCCESS: "Header details get data successfully! ",
    CARD_ADDED: "Card data added successfully!",
    GET_CARD: "Card data get successfully!",
    IMAGEICON_ADDED: "Image icon added successfully!",
    GET_IMAGE_DATA: "Image data get successfully!",
    REVIEWS_ADDED: "Reviews created successfully!",
    GET_REVIEWS: "Rviews data get successfully!",
    CONTENT_ADDED: "Content data added successfully!",
    GET_CONTENT: "Content data get........!",
    HELP_ADDED: "Help data added successfully!",
    SECTION_ADDED: "Section data added successfully!",
    DEMO_ADDED: "Demo data added successfully!",
    BLOG_ADDED: "Blog data added successfully!",
    BLOG_DATA_LIST: "Blog data list!",
    BLOG_UPDATED: "Blog data updated successfully!",
    BLOG_DELETED: "Blog data deleted successfully!",
    ECOMMERCE_ADDED: "E-commerce data added successfully!"
}
module.exports = {
    message
}